// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv0uxwSA6DNp6MV3TJJ94SSxaJZTrreKA',
    appId: '1:496473083024:web:64cb8f3e0acd87ff549c15',
    messagingSenderId: '496473083024',
    projectId: 'my-chat-app-fc4d2',
    authDomain: 'my-chat-app-fc4d2.firebaseapp.com',
    storageBucket: 'my-chat-app-fc4d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0NhhtrOhvZ2WsO-9oHu6GnbH7YH9QfLY',
    appId: '1:496473083024:android:b388aa6c6c59ac10549c15',
    messagingSenderId: '496473083024',
    projectId: 'my-chat-app-fc4d2',
    storageBucket: 'my-chat-app-fc4d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl6dThIRrjI4fc9YOrlzMct0CjlSGF64U',
    appId: '1:496473083024:ios:9edbd88c899cd822549c15',
    messagingSenderId: '496473083024',
    projectId: 'my-chat-app-fc4d2',
    storageBucket: 'my-chat-app-fc4d2.appspot.com',
    iosClientId: '496473083024-9oqrqnkc7l3vhvp2mk8tveu90m090cmi.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl6dThIRrjI4fc9YOrlzMct0CjlSGF64U',
    appId: '1:496473083024:ios:9edbd88c899cd822549c15',
    messagingSenderId: '496473083024',
    projectId: 'my-chat-app-fc4d2',
    storageBucket: 'my-chat-app-fc4d2.appspot.com',
    iosClientId: '496473083024-9oqrqnkc7l3vhvp2mk8tveu90m090cmi.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutterChatApp',
  );
}
